server:
  port: 8080
spring:
  cloud:
    gateway:
      default-filters: # default-filters下的过滤器可以作用于所有路由
        - AddRequestHeader=key, value
      routes:
        - id: item # 路由规则id，自定义，唯一
          uri: lb://item-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/item/**,/search/** # 这里是以请求路径作为判断规则
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**,/address/**
        - id: pay
          uri: lb://pay-service
          predicates:
            - Path=/pay-order/**
        - id: trade
          uri: lb://trade-service
          predicates:
            - Path=/order/**
tw:
 auth:
    excludePaths:
      - /search/**
      - /user/login
      - /user/code
